# === BOT CONFIG (rename to config.yaml and fill your keys) ===
bybit:
  api_key: "PUT_YOUR_API_KEY"
  api_secret: "PUT_YOUR_API_SECRET"
  testnet: true         # set false for live

trading:
  symbol: "BTCUSDT"
  category: "linear"    # 'linear' for USDT perps
  timeframe: "5"        # minutes. Allowed: 1,3,5,15,30,60,120,240,360,720,1440
  ema_length: 20
  atr_length: 14
  lookback: 4
  risk_pct: 0.5         # fixed 0.5% per trade
  rr_ratio: 4.0         # TP distance = rr_ratio * SL distance
  enable_long: true
  enable_short: true
  leverage: 5           # set at exchange separately if needed
  min_qty: 0.001        # guardrail for tiny accounts/symbols

fees:
  taker: 0.0004         # 0.04% taker
  maker: 0.0002         # optional, unused if market orders

engine:
  poll_seconds: 10      # how often to check for new closed candle
  db_path: "bot.db"     # sqlite file
  report_path: "report.html"
